version: '3.4'

networks:
  concerto: {}
  meet-jitsi: {}

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.0
    volumes:
      - ${CONCERTO_VOLUME_PATH}/keycloak:/var/lib/keycloak/data
    environment:
      KC_DB_USERNAME:
      KC_DB_PASSWORD:
      KC_DB:
      KC_DB_URL:
      
      KEYCLOAK_ADMIN:
      KEYCLOAK_ADMIN_PASSWORD:
      
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: ${KEYCLOAK_BASE_PATH}/
      
      KC_HOSTNAME_PATH: ${KEYCLOAK_BASE_PATH}/
      KC_HOSTNAME_URL: ${KEYCLOAK_BASE_URL:?}/
      KC_HOSTNAME_ADMIN_URL: ${KEYCLOAK_BASE_URL:?}/
      KC_HOSTNAME_STRICT_HTTPS: "false"
    command:
      - start 
    networks:
      concerto:
    ports:
      - 8080:80
    restart: unless-stopped


  postgres:
    image: postgres:15.0
    volumes:
      - ${CONCERTO_VOLUME_PATH}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    networks:
      concerto:
    ports:
      - 5432:5432


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 7100:80
    volumes:
      - ${CONCERTO_VOLUME_PATH}/pgadmin:/var/lib/pgadmin
    networks:
     - concerto


  jitsi_web:
    image: jitsi/web:${JITSI_VERSION}
    volumes:
     - ${CONCERTO_VOLUME_PATH}/jitsi_config/web:/config
     - ${CONCERTO_VOLUME_PATH}/jitsi_config/web/crontabs:/var/spool/cron/crontabs
     - ${CONCERTO_VOLUME_PATH}/transcripts:/usr/share/jitsi-meet/transcripts
    environment:
      ENABLE_AUTH: 1
      DISABLE_HTTPS: 0
      ENABLE_RECORDING: 1
      TZ: UTC

      PUBLIC_URL: ${JITSI_BASE_URL:?}/
      TOKEN_AUTH_URL: ${CONCERTO_BASE_URL:?}/auth/room/{room}

      XMPP_AUTH_DOMAIN: auth.meet-jitsi
      XMPP_BOSH_URL_BASE: http://xmpp.meet-jitsi:5280
      XMPP_DOMAIN: meet-jitsi
      XMPP_GUEST_DOMAIN: guest.meet-jitsi
      XMPP_MUC_DOMAIN: muc.meet-jitsi
      XMPP_RECORDER_DOMAIN: recorder.meet-jitsi

    networks:
      meet-jitsi:
        aliases:
        - jitsi_web
        - ${JITSI_DOMAIN:?}

  jitsi_jvb:
    image: jitsi/jvb:${JITSI_VERSION}
    volumes:
      - ${CONCERTO_VOLUME_PATH}/jitsi_config/jvb:/config
    ports:
      - ${JITSI_UDP_PORT:?}:${JITSI_UDP_PORT:?}/udp

    environment:
      DISABLE_HTTPS: 1
      SENTRY_DSN: '0'
      TZ: UTC

      PUBLIC_URL: ${JITSI_BASE_URL:?}/
      TOKEN_AUTH_URL: ${CONCERTO_BASE_URL:?}/jitsi-auth/room/{room}

      JVB_PORT: ${JITSI_UDP_PORT:?}
      JVB_ADVERTISE_IPS: ${JITSI_PUBLIC_IP:?}
      JVB_WS_SERVER_ID: jvb.meet-jitsi
      JVB_AUTH_PASSWORD:

      XMPP_AUTH_DOMAIN: auth.meet-jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet-jitsi
      XMPP_SERVER: xmpp.meet-jitsi

    entrypoint: sh -c "sed -i 's/ip route get 1/ip route get ${SWARM_INGRESS_SUBNET:-1}/' /etc/cont-init.d/10-config && exec /init"

    networks:
      meet-jitsi:
        aliases:
          - jvb.meet-jitsi

  jitsi_jicofo:
    image: jitsi/jicofo:${JITSI_VERSION}
    volumes:
      - ${CONCERTO_VOLUME_PATH}/jitsi_config/jicofo:/config
    environment:
      ENABLE_AUTH: 1
      DISABLE_HTTPS: 1
      ENABLE_RECORDING: 1
      SENTRY_DSN: '0'
      TZ: UTC

      AUTH_TYPE: jwt
      JWT_APP_SECRET: ${JITSI_JWT_SECRET}
      JICOFO_AUTH_PASSWORD:

      XMPP_AUTH_DOMAIN: auth.meet-jitsi
      XMPP_DOMAIN: meet-jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet-jitsi
      XMPP_MUC_DOMAIN: muc.meet-jitsi
      XMPP_RECORDER_DOMAIN: recorder.meet-jitsi
      XMPP_SERVER: xmpp.meet-jitsi
    networks:
        meet-jitsi:
        concerto:


  jitsi_prosody:
    image: jitsi/prosody:${JITSI_VERSION}
    volumes:
      - ${CONCERTO_VOLUME_PATH}/jitsi_config/prosody/config:/config
      - ${CONCERTO_VOLUME_PATH}/jitsi_config/prosody/prosody-plugins-custom:/prosody-plugins-custom
    environment:
      ENABLE_AUTH: 1
      ENABLE_GUESTS: 1
      DISABLE_HTTPS: 1
      ENABLE_RECORDING: 1
      PUBLIC_URL: ${JITSI_BASE_URL:?}/
      TZ: UTC

      AUTH_TYPE: jwt
      JWT_APP_ID: jitsi
      JWT_APP_SECRET: ${JITSI_JWT_SECRET}
      JIBRI_RECORDER_PASSWORD:
      JIBRI_XMPP_PASSWORD:
      JICOFO_AUTH_PASSWORD:
      JIGASI_XMPP_PASSWORD:
      JVB_AUTH_PASSWORD:

      ENABLE_END_CONFERENCE: 0

      XMPP_AUTH_DOMAIN: auth.meet-jitsi
      XMPP_DOMAIN: meet-jitsi
      XMPP_GUEST_DOMAIN: guest.meet-jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet-jitsi
      XMPP_MUC_DOMAIN: muc.meet-jitsi
      XMPP_RECORDER_DOMAIN: recorder.meet-jitsi
    networks:
      meet-jitsi:
        aliases:
          - meet-jitsi
          - xmpp.meet-jitsi
          - auth.meet-jitsi
          - guest.meet-jitsi
          - muc.meet-jitsi
          - internal-muc.meet-jitsi
          - focus.meet-jitsi
          - recorder.meet-jitsi


  jitsi_jibri:
    image: jitsi/jibri:${JITSI_VERSION}
    volumes:
    - ${CONCERTO_VOLUME_PATH}/recordings:/srv/concerto/recordings
    - ${CONCERTO_VOLUME_PATH}/jitsi_config/jibri:/config
    - type: tmpfs
      target: /dev/shm
      tmpfs:
        size: 2147483648 # 2GB
    environment:
      DISABLE_HTTPS: 1
      DISPLAY: :0
      TZ: UTC
      PUBLIC_URL: ${JITSI_BASE_URL:?}/
      CHROMIUM_FLAGS: --ignore-certificate-errors,--disable-web-security,--disable-dev-shm-usage,--start-maximized,--kiosk,--enabled,--disable-infobars,--autoplay-policy=no-user-gesture-required

      JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /defaults/finalize.sh
      JIBRI_RECORDING_DIR: /srv/concerto/recordings

      JIBRI_RECORDER_PASSWORD:
      JIBRI_XMPP_PASSWORD:

      XMPP_AUTH_DOMAIN: auth.meet-jitsi
      XMPP_DOMAIN: meet-jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet-jitsi
      XMPP_MUC_DOMAIN: muc.meet-jitsi
      XMPP_RECORDER_DOMAIN: recorder.meet-jitsi
      XMPP_SERVER: xmpp.meet-jitsi
    networks:
        meet-jitsi:
        concerto:
    cap_add:
    - SYS_ADMIN