--
-- PostgreSQL database dump
--

-- Dumped from database version 15.0 (Debian 15.0-1.pgdg110+1)
-- Dumped by pg_dump version 15.0 (Debian 15.0-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Comments; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Comments" (
    "Id" bigint NOT NULL,
    "AuthorId" uuid NOT NULL,
    "PostId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Edited" boolean NOT NULL,
    "Content" text NOT NULL
);


ALTER TABLE public."Comments" OWNER TO admin;

--
-- Name: Comments_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Comments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Comments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DawProjects; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."DawProjects" (
    "ProjectId" bigint NOT NULL,
    "AudioSourceHash" text,
    "AudioSourceGuid" uuid
);


ALTER TABLE public."DawProjects" OWNER TO admin;

--
-- Name: DawProjects_ProjectId_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."DawProjects" ALTER COLUMN "ProjectId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DawProjects_ProjectId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Folders; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Folders" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Type" integer NOT NULL,
    "WorkspaceId" bigint NOT NULL,
    "OwnerId" uuid,
    "ParentId" bigint,
    "WorkspacePermission_Type" integer NOT NULL,
    "WorkspacePermission_Inherited" boolean NOT NULL
);


ALTER TABLE public."Folders" OWNER TO admin;

--
-- Name: Folders_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Folders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Folders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Post; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Post" (
    "Id" bigint NOT NULL,
    "AuthorId" uuid NOT NULL,
    "WorkspaceId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "Edited" boolean NOT NULL
);


ALTER TABLE public."Post" OWNER TO admin;

--
-- Name: PostUploadedFile; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."PostUploadedFile" (
    "PostId" bigint NOT NULL,
    "ReferencedFilesId" bigint NOT NULL
);


ALTER TABLE public."PostUploadedFile" OWNER TO admin;

--
-- Name: Post_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Post" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Post_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sessions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Sessions" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "ScheduledDate" timestamp with time zone NOT NULL,
    "WorkspaceId" bigint NOT NULL,
    "FolderId" bigint NOT NULL,
    "MeetingGuid" uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public."Sessions" OWNER TO admin;

--
-- Name: Sessions_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Sessions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sessions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tracks; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Tracks" (
    "Id" bigint NOT NULL,
    "ProjectId" bigint NOT NULL,
    "Order" integer NOT NULL,
    "Name" text NOT NULL,
    "StartTime" real NOT NULL,
    "Volume" real NOT NULL,
    "SelectedByUserId" uuid,
    "AudioSourceGuid" uuid
);


ALTER TABLE public."Tracks" OWNER TO admin;

--
-- Name: Tracks_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Tracks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tracks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UploadedFiles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."UploadedFiles" (
    "Id" bigint NOT NULL,
    "FolderId" bigint NOT NULL,
    "OwnerId" uuid,
    "Size" bigint NOT NULL,
    "DisplayName" text NOT NULL,
    "Extension" text NOT NULL,
    "MimeType" text NOT NULL,
    "StorageName" text NOT NULL
);


ALTER TABLE public."UploadedFiles" OWNER TO admin;

--
-- Name: UploadedFiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."UploadedFiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UploadedFiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserFolderPermissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."UserFolderPermissions" (
    "UserId" uuid NOT NULL,
    "FolderId" bigint NOT NULL,
    "Permission_Type" integer NOT NULL,
    "Permission_Inherited" boolean NOT NULL
);


ALTER TABLE public."UserFolderPermissions" OWNER TO admin;

--
-- Name: Users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Users" (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO admin;

--
-- Name: WorkspaceUsers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."WorkspaceUsers" (
    "WorkspaceId" bigint NOT NULL,
    "UserId" uuid NOT NULL,
    "Role" integer NOT NULL
);


ALTER TABLE public."WorkspaceUsers" OWNER TO admin;

--
-- Name: Workspaces; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Workspaces" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "RootFolderId" bigint,
    "SessionsFolderId" bigint
);


ALTER TABLE public."Workspaces" OWNER TO admin;

--
-- Name: Workspaces_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Workspaces" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Workspaces_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin;

--
-- Data for Name: Comments; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Comments" ("Id", "AuthorId", "PostId", "CreatedAt", "Edited", "Content") FROM stdin;
1	1b47e0c0-668d-4020-959c-412c241fdd05	1	2025-05-06 20:17:23.684449+00	f	lol
2	1b47e0c0-668d-4020-959c-412c241fdd05	1	2025-05-06 20:17:29.695691+00	f	beka
\.


--
-- Data for Name: DawProjects; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."DawProjects" ("ProjectId", "AudioSourceHash", "AudioSourceGuid") FROM stdin;
1	\N	\N
\.


--
-- Data for Name: Folders; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Folders" ("Id", "Name", "Type", "WorkspaceId", "OwnerId", "ParentId", "WorkspacePermission_Type", "WorkspacePermission_Inherited") FROM stdin;
1	Root	0	3	\N	\N	0	f
2	Sessions	1	3	\N	\N	0	f
3	nowa sesja	1	3	1b47e0c0-668d-4020-959c-412c241fdd05	2	1	f
\.


--
-- Data for Name: Post; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Post" ("Id", "AuthorId", "WorkspaceId", "CreatedAt", "Title", "Content", "Edited") FROM stdin;
1	1b47e0c0-668d-4020-959c-412c241fdd05	3	2025-05-06 20:17:18.324553+00	jlijloij	greh5re\n	f
\.


--
-- Data for Name: PostUploadedFile; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."PostUploadedFile" ("PostId", "ReferencedFilesId") FROM stdin;
\.


--
-- Data for Name: Sessions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Sessions" ("Id", "Name", "ScheduledDate", "WorkspaceId", "FolderId", "MeetingGuid") FROM stdin;
1	nowa sesja	2025-05-07 20:15:14.832+00	3	3	438ba6fe-4a8b-417c-90bd-48353321e78c
\.


--
-- Data for Name: Tracks; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Tracks" ("Id", "ProjectId", "Order", "Name", "StartTime", "Volume", "SelectedByUserId", "AudioSourceGuid") FROM stdin;
1	1	0		0	1	\N	\N
2	1	0		0	1	\N	\N
\.


--
-- Data for Name: UploadedFiles; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."UploadedFiles" ("Id", "FolderId", "OwnerId", "Size", "DisplayName", "Extension", "MimeType", "StorageName") FROM stdin;
1	2	1b47e0c0-668d-4020-959c-412c241fdd05	593762	ZBS - Tunelowanie	.pdf	application/pdf	ZBS - Tunelowanie.pdf.babc9b7c-bc2a-4c39-813a-6f27d1ab6729
2	2	1b47e0c0-668d-4020-959c-412c241fdd05	316438	TuneleIPv6-IPSec	.pdf	application/pdf	TuneleIPv6-IPSec.pdf.a6c349b6-41d5-4a41-ad55-8552423a92e2
3	2	1b47e0c0-668d-4020-959c-412c241fdd05	3207030	recording-16.04.2025,-23-39-59	.wav	audio/wav	recording-16.04.2025,-23-39-59.wav.b10af852-f1df-4f93-a84b-9f5f1b4e5066
\.


--
-- Data for Name: UserFolderPermissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."UserFolderPermissions" ("UserId", "FolderId", "Permission_Type", "Permission_Inherited") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Users" ("Id", "Username", "FirstName", "LastName") FROM stdin;
1b47e0c0-668d-4020-959c-412c241fdd05	admin	admin123	admin
\.


--
-- Data for Name: WorkspaceUsers; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."WorkspaceUsers" ("WorkspaceId", "UserId", "Role") FROM stdin;
3	1b47e0c0-668d-4020-959c-412c241fdd05	0
\.


--
-- Data for Name: Workspaces; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Workspaces" ("Id", "Name", "Description", "CreatedDate", "RootFolderId", "SessionsFolderId") FROM stdin;
3	test workspace		2025-05-06 20:14:37.042348+00	1	2
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240603215141_Initial	7.0.5
\.


--
-- Name: Comments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Comments_Id_seq"', 2, true);


--
-- Name: DawProjects_ProjectId_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."DawProjects_ProjectId_seq"', 1, false);


--
-- Name: Folders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Folders_Id_seq"', 3, true);


--
-- Name: Post_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Post_Id_seq"', 1, true);


--
-- Name: Sessions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Sessions_Id_seq"', 1, true);


--
-- Name: Tracks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Tracks_Id_seq"', 2, true);


--
-- Name: UploadedFiles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."UploadedFiles_Id_seq"', 3, true);


--
-- Name: Workspaces_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Workspaces_Id_seq"', 3, true);


--
-- Name: Comments PK_Comments; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "PK_Comments" PRIMARY KEY ("Id");


--
-- Name: DawProjects PK_DawProjects; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."DawProjects"
    ADD CONSTRAINT "PK_DawProjects" PRIMARY KEY ("ProjectId");


--
-- Name: Folders PK_Folders; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Folders"
    ADD CONSTRAINT "PK_Folders" PRIMARY KEY ("Id");


--
-- Name: Post PK_Post; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Post"
    ADD CONSTRAINT "PK_Post" PRIMARY KEY ("Id");


--
-- Name: PostUploadedFile PK_PostUploadedFile; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."PostUploadedFile"
    ADD CONSTRAINT "PK_PostUploadedFile" PRIMARY KEY ("PostId", "ReferencedFilesId");


--
-- Name: Sessions PK_Sessions; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id");


--
-- Name: Tracks PK_Tracks; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Tracks"
    ADD CONSTRAINT "PK_Tracks" PRIMARY KEY ("ProjectId", "Id");


--
-- Name: UploadedFiles PK_UploadedFiles; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UploadedFiles"
    ADD CONSTRAINT "PK_UploadedFiles" PRIMARY KEY ("Id");


--
-- Name: UserFolderPermissions PK_UserFolderPermissions; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UserFolderPermissions"
    ADD CONSTRAINT "PK_UserFolderPermissions" PRIMARY KEY ("UserId", "FolderId");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: WorkspaceUsers PK_WorkspaceUsers; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."WorkspaceUsers"
    ADD CONSTRAINT "PK_WorkspaceUsers" PRIMARY KEY ("WorkspaceId", "UserId");


--
-- Name: Workspaces PK_Workspaces; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Workspaces"
    ADD CONSTRAINT "PK_Workspaces" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Comments_AuthorId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Comments_AuthorId" ON public."Comments" USING btree ("AuthorId");


--
-- Name: IX_Comments_PostId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Comments_PostId" ON public."Comments" USING btree ("PostId");


--
-- Name: IX_Folders_OwnerId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Folders_OwnerId" ON public."Folders" USING btree ("OwnerId");


--
-- Name: IX_Folders_ParentId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Folders_ParentId" ON public."Folders" USING btree ("ParentId");


--
-- Name: IX_Folders_WorkspaceId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Folders_WorkspaceId" ON public."Folders" USING btree ("WorkspaceId");


--
-- Name: IX_PostUploadedFile_ReferencedFilesId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_PostUploadedFile_ReferencedFilesId" ON public."PostUploadedFile" USING btree ("ReferencedFilesId");


--
-- Name: IX_Post_AuthorId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Post_AuthorId" ON public."Post" USING btree ("AuthorId");


--
-- Name: IX_Post_WorkspaceId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Post_WorkspaceId" ON public."Post" USING btree ("WorkspaceId");


--
-- Name: IX_Sessions_FolderId; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX "IX_Sessions_FolderId" ON public."Sessions" USING btree ("FolderId");


--
-- Name: IX_Sessions_MeetingGuid; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Sessions_MeetingGuid" ON public."Sessions" USING btree ("MeetingGuid");


--
-- Name: IX_Sessions_WorkspaceId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Sessions_WorkspaceId" ON public."Sessions" USING btree ("WorkspaceId");


--
-- Name: IX_Tracks_SelectedByUserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Tracks_SelectedByUserId" ON public."Tracks" USING btree ("SelectedByUserId");


--
-- Name: IX_UploadedFiles_FolderId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_UploadedFiles_FolderId" ON public."UploadedFiles" USING btree ("FolderId");


--
-- Name: IX_UploadedFiles_OwnerId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_UploadedFiles_OwnerId" ON public."UploadedFiles" USING btree ("OwnerId");


--
-- Name: IX_UserFolderPermissions_FolderId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_UserFolderPermissions_FolderId" ON public."UserFolderPermissions" USING btree ("FolderId");


--
-- Name: IX_UserFolderPermissions_UserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_UserFolderPermissions_UserId" ON public."UserFolderPermissions" USING btree ("UserId");


--
-- Name: IX_WorkspaceUsers_UserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_WorkspaceUsers_UserId" ON public."WorkspaceUsers" USING btree ("UserId");


--
-- Name: IX_WorkspaceUsers_WorkspaceId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_WorkspaceUsers_WorkspaceId" ON public."WorkspaceUsers" USING btree ("WorkspaceId");


--
-- Name: IX_Workspaces_RootFolderId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Workspaces_RootFolderId" ON public."Workspaces" USING btree ("RootFolderId");


--
-- Name: IX_Workspaces_SessionsFolderId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Workspaces_SessionsFolderId" ON public."Workspaces" USING btree ("SessionsFolderId");


--
-- Name: Comments FK_Comments_Post_PostId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_Post_PostId" FOREIGN KEY ("PostId") REFERENCES public."Post"("Id") ON DELETE CASCADE;


--
-- Name: Comments FK_Comments_Users_AuthorId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Folders FK_Folders_Folders_ParentId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Folders"
    ADD CONSTRAINT "FK_Folders_Folders_ParentId" FOREIGN KEY ("ParentId") REFERENCES public."Folders"("Id") ON DELETE CASCADE;


--
-- Name: Folders FK_Folders_Users_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Folders"
    ADD CONSTRAINT "FK_Folders_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: Folders FK_Folders_Workspaces_WorkspaceId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Folders"
    ADD CONSTRAINT "FK_Folders_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES public."Workspaces"("Id") ON DELETE CASCADE;


--
-- Name: PostUploadedFile FK_PostUploadedFile_Post_PostId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."PostUploadedFile"
    ADD CONSTRAINT "FK_PostUploadedFile_Post_PostId" FOREIGN KEY ("PostId") REFERENCES public."Post"("Id") ON DELETE CASCADE;


--
-- Name: PostUploadedFile FK_PostUploadedFile_UploadedFiles_ReferencedFilesId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."PostUploadedFile"
    ADD CONSTRAINT "FK_PostUploadedFile_UploadedFiles_ReferencedFilesId" FOREIGN KEY ("ReferencedFilesId") REFERENCES public."UploadedFiles"("Id") ON DELETE CASCADE;


--
-- Name: Post FK_Post_Users_AuthorId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Post"
    ADD CONSTRAINT "FK_Post_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Post FK_Post_Workspaces_WorkspaceId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Post"
    ADD CONSTRAINT "FK_Post_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES public."Workspaces"("Id") ON DELETE CASCADE;


--
-- Name: Sessions FK_Sessions_Folders_FolderId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "FK_Sessions_Folders_FolderId" FOREIGN KEY ("FolderId") REFERENCES public."Folders"("Id") ON DELETE SET NULL;


--
-- Name: Sessions FK_Sessions_Workspaces_WorkspaceId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "FK_Sessions_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES public."Workspaces"("Id") ON DELETE CASCADE;


--
-- Name: Tracks FK_Tracks_DawProjects_ProjectId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Tracks"
    ADD CONSTRAINT "FK_Tracks_DawProjects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public."DawProjects"("ProjectId") ON DELETE CASCADE;


--
-- Name: Tracks FK_Tracks_Users_SelectedByUserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Tracks"
    ADD CONSTRAINT "FK_Tracks_Users_SelectedByUserId" FOREIGN KEY ("SelectedByUserId") REFERENCES public."Users"("Id");


--
-- Name: UploadedFiles FK_UploadedFiles_Folders_FolderId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UploadedFiles"
    ADD CONSTRAINT "FK_UploadedFiles_Folders_FolderId" FOREIGN KEY ("FolderId") REFERENCES public."Folders"("Id") ON DELETE CASCADE;


--
-- Name: UploadedFiles FK_UploadedFiles_Users_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UploadedFiles"
    ADD CONSTRAINT "FK_UploadedFiles_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES public."Users"("Id");


--
-- Name: UserFolderPermissions FK_UserFolderPermissions_Folders_FolderId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UserFolderPermissions"
    ADD CONSTRAINT "FK_UserFolderPermissions_Folders_FolderId" FOREIGN KEY ("FolderId") REFERENCES public."Folders"("Id") ON DELETE CASCADE;


--
-- Name: UserFolderPermissions FK_UserFolderPermissions_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UserFolderPermissions"
    ADD CONSTRAINT "FK_UserFolderPermissions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: WorkspaceUsers FK_WorkspaceUsers_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."WorkspaceUsers"
    ADD CONSTRAINT "FK_WorkspaceUsers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: WorkspaceUsers FK_WorkspaceUsers_Workspaces_WorkspaceId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."WorkspaceUsers"
    ADD CONSTRAINT "FK_WorkspaceUsers_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES public."Workspaces"("Id") ON DELETE CASCADE;


--
-- Name: Workspaces FK_Workspaces_Folders_RootFolderId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Workspaces"
    ADD CONSTRAINT "FK_Workspaces_Folders_RootFolderId" FOREIGN KEY ("RootFolderId") REFERENCES public."Folders"("Id");


--
-- Name: Workspaces FK_Workspaces_Folders_SessionsFolderId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Workspaces"
    ADD CONSTRAINT "FK_Workspaces_Folders_SessionsFolderId" FOREIGN KEY ("SessionsFolderId") REFERENCES public."Folders"("Id");


--
-- PostgreSQL database dump complete
--

