// <auto-generated />
using System;
using Concerto.Server.Data.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concerto.Server.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20220921150609_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concerto.Server.Data.Models.ChatMessage", b =>
                {
                    b.Property<long>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatMessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SendTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            ChatMessageId = 1L,
                            Content = "Test message 1",
                            ConversationId = 1L,
                            SendTimestamp = new DateTime(2022, 9, 21, 15, 1, 9, 494, DateTimeKind.Utc).AddTicks(9950),
                            SenderId = 1L
                        },
                        new
                        {
                            ChatMessageId = 2L,
                            Content = "Test message 2",
                            ConversationId = 1L,
                            SendTimestamp = new DateTime(2022, 9, 21, 15, 3, 9, 494, DateTimeKind.Utc).AddTicks(9954),
                            SenderId = 1L
                        },
                        new
                        {
                            ChatMessageId = 3L,
                            Content = "Test reply 1",
                            ConversationId = 1L,
                            SendTimestamp = new DateTime(2022, 9, 21, 15, 4, 9, 494, DateTimeKind.Utc).AddTicks(9954),
                            SenderId = 2L
                        },
                        new
                        {
                            ChatMessageId = 4L,
                            Content = "Test reply 2",
                            ConversationId = 1L,
                            SendTimestamp = new DateTime(2022, 9, 21, 15, 5, 9, 494, DateTimeKind.Utc).AddTicks(9955),
                            SenderId = 2L
                        },
                        new
                        {
                            ChatMessageId = 5L,
                            Content = "Test message 3",
                            ConversationId = 1L,
                            SendTimestamp = new DateTime(2022, 9, 21, 15, 5, 9, 494, DateTimeKind.Utc).AddTicks(9956),
                            SenderId = 1L
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Contact", b =>
                {
                    b.Property<long>("User1Id")
                        .HasColumnType("bigint");

                    b.Property<long>("User2Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("User1Id", "User2Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            User1Id = 1L,
                            User2Id = 2L,
                            Status = 1
                        },
                        new
                        {
                            User1Id = 1L,
                            User2Id = 3L,
                            Status = 1
                        },
                        new
                        {
                            User1Id = 1L,
                            User2Id = 4L,
                            Status = 1
                        },
                        new
                        {
                            User1Id = 2L,
                            User2Id = 3L,
                            Status = 1
                        },
                        new
                        {
                            User1Id = 2L,
                            User2Id = 4L,
                            Status = 1
                        },
                        new
                        {
                            User1Id = 3L,
                            User2Id = 4L,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Conversation", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConversationId"));

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.HasKey("ConversationId");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            ConversationId = 1L,
                            IsPrivate = true
                        },
                        new
                        {
                            ConversationId = 2L,
                            IsPrivate = true
                        },
                        new
                        {
                            ConversationId = 3L,
                            IsPrivate = true
                        },
                        new
                        {
                            ConversationId = 4L,
                            IsPrivate = true
                        },
                        new
                        {
                            ConversationId = 5L,
                            IsPrivate = true
                        },
                        new
                        {
                            ConversationId = 6L,
                            IsPrivate = true
                        },
                        new
                        {
                            ConversationId = 7L,
                            IsPrivate = false
                        },
                        new
                        {
                            ConversationId = 8L,
                            IsPrivate = false
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.ConversationUser", b =>
                {
                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationUser");

                    b.HasData(
                        new
                        {
                            ConversationId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            ConversationId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            ConversationId = 2L,
                            UserId = 1L
                        },
                        new
                        {
                            ConversationId = 2L,
                            UserId = 3L
                        },
                        new
                        {
                            ConversationId = 3L,
                            UserId = 1L
                        },
                        new
                        {
                            ConversationId = 3L,
                            UserId = 4L
                        },
                        new
                        {
                            ConversationId = 4L,
                            UserId = 2L
                        },
                        new
                        {
                            ConversationId = 4L,
                            UserId = 3L
                        },
                        new
                        {
                            ConversationId = 5L,
                            UserId = 2L
                        },
                        new
                        {
                            ConversationId = 5L,
                            UserId = 4L
                        },
                        new
                        {
                            ConversationId = 6L,
                            UserId = 3L
                        },
                        new
                        {
                            ConversationId = 6L,
                            UserId = 4L
                        },
                        new
                        {
                            ConversationId = 7L,
                            UserId = 1L
                        },
                        new
                        {
                            ConversationId = 7L,
                            UserId = 2L
                        },
                        new
                        {
                            ConversationId = 7L,
                            UserId = 3L
                        },
                        new
                        {
                            ConversationId = 8L,
                            UserId = 1L
                        },
                        new
                        {
                            ConversationId = 8L,
                            UserId = 4L
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Room", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoomId"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoomId");

                    b.HasIndex("ConversationId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1L,
                            ConversationId = 7L,
                            Name = "Room 1"
                        },
                        new
                        {
                            RoomId = 2L,
                            ConversationId = 8L,
                            Name = "Room 2"
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.RoomUser", b =>
                {
                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("RoomId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomUsers");

                    b.HasData(
                        new
                        {
                            RoomId = 1L,
                            UserId = 1L,
                            Role = 0
                        },
                        new
                        {
                            RoomId = 1L,
                            UserId = 2L,
                            Role = 0
                        },
                        new
                        {
                            RoomId = 1L,
                            UserId = 3L,
                            Role = 0
                        },
                        new
                        {
                            RoomId = 2L,
                            UserId = 1L,
                            Role = 0
                        },
                        new
                        {
                            RoomId = 2L,
                            UserId = 4L,
                            Role = 0
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Session", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SessionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.HasIndex("RoomId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            FirstName = "Jan",
                            LastName = "Administracyjny",
                            SubjectId = new Guid("95f418ac-e38f-41ec-a2ad-828bdd3895d0"),
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2L,
                            FirstName = "Piotr",
                            LastName = "Testowy",
                            SubjectId = new Guid("954af482-22dd-483f-ac99-975144f85a04"),
                            Username = "user2"
                        },
                        new
                        {
                            UserId = 3L,
                            FirstName = "Jacek",
                            LastName = "Testowy",
                            SubjectId = new Guid("c786cbc3-9924-410f-bcdb-75a2469107be"),
                            Username = "user3"
                        },
                        new
                        {
                            UserId = 4L,
                            FirstName = "John",
                            LastName = "Smith",
                            SubjectId = new Guid("f2c0a648-82bb-44a9-908e-8006577cb276"),
                            Username = "user4"
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("Concerto.Server.Data.Models.Conversation", "Conversation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concerto.Server.Data.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Contact", b =>
                {
                    b.HasOne("Concerto.Server.Data.Models.User", "User1")
                        .WithMany("InvitedContacts")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Concerto.Server.Data.Models.User", "User2")
                        .WithMany("InvitingContacts")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.ConversationUser", b =>
                {
                    b.HasOne("Concerto.Server.Data.Models.Conversation", "Conversation")
                        .WithMany("ConversationUsers")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Concerto.Server.Data.Models.User", "User")
                        .WithMany("ConversationsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Room", b =>
                {
                    b.HasOne("Concerto.Server.Data.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.RoomUser", b =>
                {
                    b.HasOne("Concerto.Server.Data.Models.Room", "Room")
                        .WithMany("RoomUsers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Concerto.Server.Data.Models.User", "User")
                        .WithMany("RoomsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Session", b =>
                {
                    b.HasOne("Concerto.Server.Data.Models.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Conversation", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ConversationUsers");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.Room", b =>
                {
                    b.Navigation("RoomUsers");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.User", b =>
                {
                    b.Navigation("ConversationsUser");

                    b.Navigation("InvitedContacts");

                    b.Navigation("InvitingContacts");

                    b.Navigation("RoomsUser");
                });
#pragma warning restore 612, 618
        }
    }
}
