// <auto-generated />
using System;
using Concerto.Server.Data.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concerto.Server.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20220803004329_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concerto.Server.Data.Models.ChatMessage", b =>
                {
                    b.Property<long>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatMessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SendTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            ChatMessageId = 1L,
                            Content = "Test message 1",
                            RecipientId = 2L,
                            SendTimestamp = new DateTime(2022, 8, 3, 0, 38, 29, 10, DateTimeKind.Utc).AddTicks(5666),
                            SenderId = 1L
                        },
                        new
                        {
                            ChatMessageId = 2L,
                            Content = "Test message 2",
                            RecipientId = 2L,
                            SendTimestamp = new DateTime(2022, 8, 3, 0, 40, 29, 10, DateTimeKind.Utc).AddTicks(5670),
                            SenderId = 1L
                        },
                        new
                        {
                            ChatMessageId = 3L,
                            Content = "Test message 3",
                            RecipientId = 2L,
                            SendTimestamp = new DateTime(2022, 8, 3, 0, 42, 29, 10, DateTimeKind.Utc).AddTicks(5671),
                            SenderId = 3L
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            FirstName = "Jan",
                            LastName = "Administracyjny",
                            SubjectId = new Guid("95f418ac-e38f-41ec-a2ad-828bdd3895d0"),
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2L,
                            FirstName = "Piotr",
                            LastName = "Testowy",
                            SubjectId = new Guid("954af482-22dd-483f-ac99-975144f85a04"),
                            Username = "user2"
                        },
                        new
                        {
                            UserId = 3L,
                            FirstName = "Jacek",
                            LastName = "Testowy",
                            SubjectId = new Guid("c786cbc3-9924-410f-bcdb-75a2469107be"),
                            Username = "user3"
                        },
                        new
                        {
                            UserId = 4L,
                            FirstName = "John",
                            LastName = "Smith",
                            SubjectId = new Guid("f2c0a648-82bb-44a9-908e-8006577cb276"),
                            Username = "user4"
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.UserContact", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("UserContacts");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            ContactId = 2L
                        },
                        new
                        {
                            UserId = 2L,
                            ContactId = 1L
                        },
                        new
                        {
                            UserId = 1L,
                            ContactId = 3L
                        },
                        new
                        {
                            UserId = 1L,
                            ContactId = 4L
                        });
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("Concerto.Server.Data.Models.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concerto.Server.Data.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.UserContact", b =>
                {
                    b.HasOne("Concerto.Server.Data.Models.User", "Contact")
                        .WithMany("ContactOf")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Concerto.Server.Data.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concerto.Server.Data.Models.User", b =>
                {
                    b.Navigation("ContactOf");

                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
